// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzq45LJKP4Paz0UsodELjiPcfZg8dJqPA',
    appId: '1:472718972665:web:426db7b86d306785c33428',
    messagingSenderId: '472718972665',
    projectId: 'aplikasi-sekolah-db9f6',
    authDomain: 'aplikasi-sekolah-db9f6.firebaseapp.com',
    storageBucket: 'aplikasi-sekolah-db9f6.firebasestorage.app',
    measurementId: 'G-VZWNQFXN6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyFGBD0Ww5dYzJIv9BhXjbaRemBKPuCgE',
    appId: '1:472718972665:android:ef7898d8ad0b96c9c33428',
    messagingSenderId: '472718972665',
    projectId: 'aplikasi-sekolah-db9f6',
    storageBucket: 'aplikasi-sekolah-db9f6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj3-enm5tWyvngHI9SryK3-A8Y0SKotCE',
    appId: '1:472718972665:ios:a39e599d54f2a768c33428',
    messagingSenderId: '472718972665',
    projectId: 'aplikasi-sekolah-db9f6',
    storageBucket: 'aplikasi-sekolah-db9f6.firebasestorage.app',
    androidClientId: '472718972665-4cr72u0uca8bj8jvi152eqq5lg97b3es.apps.googleusercontent.com',
    iosClientId: '472718972665-idd9ioss1r559kpckn2qrr867cqta2q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLmsApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj3-enm5tWyvngHI9SryK3-A8Y0SKotCE',
    appId: '1:472718972665:ios:a39e599d54f2a768c33428',
    messagingSenderId: '472718972665',
    projectId: 'aplikasi-sekolah-db9f6',
    storageBucket: 'aplikasi-sekolah-db9f6.firebasestorage.app',
    androidClientId: '472718972665-4cr72u0uca8bj8jvi152eqq5lg97b3es.apps.googleusercontent.com',
    iosClientId: '472718972665-idd9ioss1r559kpckn2qrr867cqta2q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzq45LJKP4Paz0UsodELjiPcfZg8dJqPA',
    appId: '1:472718972665:web:f40bfd73cb977b09c33428',
    messagingSenderId: '472718972665',
    projectId: 'aplikasi-sekolah-db9f6',
    authDomain: 'aplikasi-sekolah-db9f6.firebaseapp.com',
    storageBucket: 'aplikasi-sekolah-db9f6.firebasestorage.app',
    measurementId: 'G-ZPKKTW4Z1E',
  );
}
